version: "3"
services:
  app:
    container_name: blog_app
    build:
      context: ./docker/php
      args:
        - TZ=Asia/Tokyo
    volumes:
      - ./src:/work
      - ./logs:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /work
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=blog
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - TZ=Asia/Tokyo
  web:
    image: nginx:1.17.1-alpine
    container_name: blog_web
    depends_on:
      - app
    ports:
      - 10080:80
    volumes:
      - ./src:/work
      - ./logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=Asia/Tokyo
  db:
    image: mysql:8.0.16
    container_name: blog_db
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=blog
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Tokyo
volumes:
  db-store:
    driver: local
