version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: blog-mysql
    environment:
      - MYSQL_DATABASE=blog
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - TZ=Japan
    networks:
      - default
    ports:
      - "3306:3306"
    volumes:
      - ./docker-image/mysql/init:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql:cached

  app:
    build: ./docker-image/php/
    container_name: blog-app
    volumes:
      - ./:/var/www/html:cached
      - vendor-data:/var/www/html/src/vendor
      - node_modules-data:/var/www/html/src/node_modules
      - ./docker-image/php/php-httpd.conf:/etc/httpd/conf.d/php-httpd.conf
    depends_on:
      - mysql
      - redis
    ports:
      - "80:80"
      - "443:443"
    networks:
      - default

  # phpdbg:
  #   build:
  #     context: ./
  #     dockerfile: docker-image/phpdbg/Dockerfile
  #   container_name: blog-phpdbg
  #   volumes:
  #     - ./src/coverage:/var/www/html/src/coverage
  #     - vendor-data:/var/www/html/src/vendor
  #     - ./docker-image/php/php-httpd.conf:/etc/httpd/conf.d/php-httpd.conf
  #   depends_on:
  #     - redis
  #   networks:
  #     - default

  mailhog:
    image: mailhog/mailhog
    container_name: blog-mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - default

  redis:
    image: redis:alpine
    container_name: blog-redis
    networks:
      - default
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data:cached

  # 今は必要ないのでコメントアウト
  #  selenium:
  #    image: selenium/standalone-chrome
  #    container_name: blog-selenium
  #    ports:
  #      - 4444:4444
  #    networks:
  #      - default

  # dynamodb:
  #   image: amazon/dynamodb-local
  #   container_name: blog-dynamodb
  #   ports:
  #     - 8000:8000
  #   command: -jar DynamoDBLocal.jar -inMemory -sharedDb
  #   networks:
  #     - default

  # dynamodb-admin:
  #   image: aaronshaf/dynamodb-admin
  #   container_name: blog-dynamodb-admin
  #   environment:
  #     - DYNAMO_ENDPOINT=http://dynamodb:8000
  #   ports:
  #     - 8001:8001
  #   networks:
  #     - default

  schemaspy:
    image: schemaspy/schemaspy
    container_name: blog-schemaspy
    volumes:
      - ./docker-image/schemaspy/output:/output
      - ./docker-image/schemaspy/drivers:/drivers
      - ./docker-image/schemaspy/schemaspy.properties:/schemaspy.properties
      - ./docker-image/schemaspy/schemaspy-meta.xml:/schemaspy-meta.xml
    networks:
      - default
    depends_on:
      - mysql

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local
  vendor-data:
    driver: local
  node_modules-data:
    driver: local

networks:
  default:
